### ISSUE TITLE
Question: Would you like notification integration on KDE integrated into the calcure?

### ISSUE THREAD

**Issue by LumenYoung** [anufrievroman/minimalist-tui-calendar#53]
Hi, aufrievroman,

Thank you for your great application, this is the exact same thing I would like to do. I would like to ask if you need some integration of KDE notifications for the events on the calendar to be published on time when using calcure? This would be not so universal and I think making a standard interface and maybe someone else using a different desktop environment might have their own notification later.

Also, for me it is interesting to use natural language to arrange event, setup today's calendar automatically (all the stuffs that can use AI to help with managing your day)

I haven't looked into the detail of the project but I think this is a great project to work on, and I would like to know if you think such feature aligns with your view of the roadmap of calcure. If that is the case, then I'm happy to contribute to the project

**Comment by anufrievroman** [comment]
Hi, thanks for your interest!
Basically, now the events don't really have "time" when they occur, they only have day, and time just displayed as text. So, there is nothing to really create notification for. I think maybe in the future we'll fully switch to .ics files and will support all the time fields, then we may think about desktop notifications...

About ai and arranging events, could you give an example how it may work?
Also, initially, the project was meant as more of a "minimalist's" calendar, assuming the user have only a few events per day. I doubt this app is really suitable for really busy people with many events every day and a need to be notified about it and use ai to sort it. I guess just because of the TUI nature of the app, it's hard to pack a lot in to this form factor.

On the other hand, I am currently thinking about ways to filter (or maybe sort too) events and tasks according to some marker, like show only important, for example. In this regard, I think it would be cool to be able to type like "show only events related to school" and then AI can figure out which once are those. But I am not sure if this feature is worse constant internet connection and all the privacy implications. Do you think things like that can work offline with a small local AI?
